[package]
name = "chaz"
version = "0.3.0"
edition = "2021"
authors = ["Patrick Jackson <patrick@jackson.dev>"]
readme = "README.md"
license = "MIT"
description = "Chaz is an AI chatbot for Matrix."
repository = "https://github.com/arcuru/chaz"
homepage = "https://github.com/arcuru/chaz"

[[bin]]
name = "chaz"
test = false

[dependencies]
headjack = { git = "https://github.com/arcuru/headjack", rev = "6db2a2e059e6bbc2f47eea3ac58be650bd484bf0" }
anyhow = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3"
tracing = "0.1"
matrix-sdk = "0.7"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
clap = { version = "4", features = ["derive"] }
lazy_static = "1"
regex = "1"
dirs = "5"
openai-api-rs = "5.0.12"
