name: Setup Nix
description: Install Nix with nix-fast-build and caching

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21
      with:
        extra-conf: |
          accept-flake-config = true

    - name: Enable Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@6221693898146dc97e38ad0e013488a16477a4c4 # v9

    - name: Install nix-fast-build
      shell: bash
      run: nix profile install nixpkgs#nix-fast-build
