name: Setup Nix
description: Install Nix with nix-fast-build

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21
      with:
        extra-conf: |
          accept-flake-config = true

    - name: Install nix-fast-build
      shell: bash
      run: nix profile install nixpkgs#nix-fast-build
