name: Codeberg Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: codeberg-mirror
  cancel-in-progress: false

jobs:
  codeberg:
    runs-on: ubicloud-standard-2
    environment: mirror
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Mirror to Codeberg
        uses: yesolutions/mirror-action@1708f16cdb28634fd3ba10c5c79abc91f5578a14 # v0.7.0
        with:
          REMOTE: git@codeberg.org:arcuru/chaz.git
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          GIT_SSH_NO_VERIFY_HOST: "true"
